// AUTOGENERATED - DO NOT EDIT MANUALLY
// This code is generated to use a TableLayoutPanel for a responsive and localizable layout.

using DemoTradingApp.Properties;

namespace DemoTradingApp
{
    partial class AddBalanceForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.kryptonManager1 = new Krypton.Toolkit.KryptonManager(this.components);
            this.kryptonPanel1 = new Krypton.Toolkit.KryptonPanel();
            this.mainTableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.groupAddBalance = new Krypton.Toolkit.KryptonGroupBox();
            this.tableLayoutPanelAdd = new System.Windows.Forms.TableLayoutPanel();
            this.kryptonLabel1 = new Krypton.Toolkit.KryptonLabel();
            this.cmbWallets = new Krypton.Toolkit.KryptonComboBox();
            this.kryptonLabel2 = new Krypton.Toolkit.KryptonLabel();
            this.numAmount = new Krypton.Toolkit.KryptonNumericUpDown();
            this.kryptonLabel3 = new Krypton.Toolkit.KryptonLabel();
            this.cmbCurrency = new Krypton.Toolkit.KryptonComboBox();
            this.btnConfirm = new Krypton.Toolkit.KryptonButton();
            this.groupRemoveBalance = new Krypton.Toolkit.KryptonGroupBox();
            this.tableLayoutPanelRemove = new System.Windows.Forms.TableLayoutPanel();
            this.kryptonLabel4 = new Krypton.Toolkit.KryptonLabel();
            this.cmbAssetToRemove = new Krypton.Toolkit.KryptonComboBox();
            this.kryptonLabel5 = new Krypton.Toolkit.KryptonLabel();
            this.numAmountToRemove = new Krypton.Toolkit.KryptonNumericUpDown();
            this.btnRemoveBalance = new Krypton.Toolkit.KryptonButton();
            this.btnCancel = new Krypton.Toolkit.KryptonButton();
            ((System.ComponentModel.ISupportInitialize)(this.kryptonPanel1)).BeginInit();
            this.kryptonPanel1.SuspendLayout();
            this.mainTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.groupAddBalance)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.groupAddBalance.Panel)).BeginInit();
            this.groupAddBalance.Panel.SuspendLayout();
            this.tableLayoutPanelAdd.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.cmbWallets)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmbCurrency)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.groupRemoveBalance)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.groupRemoveBalance.Panel)).BeginInit();
            this.groupRemoveBalance.Panel.SuspendLayout();
            this.tableLayoutPanelRemove.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.cmbAssetToRemove)).BeginInit();
            this.SuspendLayout();
            // 
            // kryptonManager1
            // 
            this.kryptonManager1.GlobalPaletteMode = Krypton.Toolkit.PaletteMode.SparkleBlue;
            // 
            // kryptonPanel1
            // 
            this.kryptonPanel1.Controls.Add(this.mainTableLayoutPanel);
            this.kryptonPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.kryptonPanel1.Location = new System.Drawing.Point(0, 0);
            this.kryptonPanel1.Name = "kryptonPanel1";
            this.kryptonPanel1.Padding = new System.Windows.Forms.Padding(10);
            this.kryptonPanel1.Size = new System.Drawing.Size(534, 561);
            this.kryptonPanel1.TabIndex = 0;
            // 
            // mainTableLayoutPanel
            // 
            this.mainTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.mainTableLayoutPanel.ColumnCount = 1;
            this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.mainTableLayoutPanel.Controls.Add(this.groupAddBalance, 0, 0);
            this.mainTableLayoutPanel.Controls.Add(this.groupRemoveBalance, 0, 1);
            this.mainTableLayoutPanel.Controls.Add(this.btnCancel, 0, 2);
            this.mainTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mainTableLayoutPanel.Location = new System.Drawing.Point(10, 10);
            this.mainTableLayoutPanel.Name = "mainTableLayoutPanel";
            this.mainTableLayoutPanel.RowCount = 3;
            this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 240F));
            this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 200F));
            this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.mainTableLayoutPanel.Size = new System.Drawing.Size(514, 541);
            this.mainTableLayoutPanel.TabIndex = 0;
            // 
            // groupAddBalance
            // 
            this.groupAddBalance.CaptionStyle = Krypton.Toolkit.LabelStyle.TitleControl;
            this.groupAddBalance.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupAddBalance.Location = new System.Drawing.Point(3, 3);
            this.groupAddBalance.Name = "groupAddBalance";
            // 
            // groupAddBalance.Panel
            // 
            this.groupAddBalance.Panel.Controls.Add(this.tableLayoutPanelAdd);
            this.groupAddBalance.Size = new System.Drawing.Size(508, 234);
            this.groupAddBalance.TabIndex = 0;
            this.groupAddBalance.Values.Heading = global::DemoTradingApp.Properties.Resources.AddBalance;
            // 
            // tableLayoutPanelAdd
            // 
            this.tableLayoutPanelAdd.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanelAdd.ColumnCount = 2;
            this.tableLayoutPanelAdd.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanelAdd.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanelAdd.Controls.Add(this.kryptonLabel1, 0, 0);
            this.tableLayoutPanelAdd.Controls.Add(this.cmbWallets, 1, 0);
            this.tableLayoutPanelAdd.Controls.Add(this.kryptonLabel2, 0, 1);
            this.tableLayoutPanelAdd.Controls.Add(this.numAmount, 1, 1);
            this.tableLayoutPanelAdd.Controls.Add(this.kryptonLabel3, 0, 2);
            this.tableLayoutPanelAdd.Controls.Add(this.cmbCurrency, 1, 2);
            this.tableLayoutPanelAdd.Controls.Add(this.btnConfirm, 1, 3);
            this.tableLayoutPanelAdd.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanelAdd.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanelAdd.Name = "tableLayoutPanelAdd";
            this.tableLayoutPanelAdd.Padding = new System.Windows.Forms.Padding(5);
            this.tableLayoutPanelAdd.RowCount = 4;
            this.tableLayoutPanelAdd.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanelAdd.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanelAdd.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanelAdd.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanelAdd.Size = new System.Drawing.Size(504, 187);
            this.tableLayoutPanelAdd.TabIndex = 0;
            // 
            // kryptonLabel1
            // 
            this.kryptonLabel1.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.kryptonLabel1.Location = new System.Drawing.Point(74, 16);
            this.kryptonLabel1.Name = "kryptonLabel1";
            this.kryptonLabel1.Size = new System.Drawing.Size(64, 24);
            this.kryptonLabel1.TabIndex = 0;
            this.kryptonLabel1.Values.Text = global::DemoTradingApp.Properties.Resources.WalletLabel;
            // 
            // cmbWallets
            // 
            this.cmbWallets.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.cmbWallets.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbWallets.DropDownWidth = 217;
            this.cmbWallets.IntegralHeight = false;
            this.cmbWallets.Location = new System.Drawing.Point(144, 15);
            this.cmbWallets.Name = "cmbWallets";
            this.cmbWallets.Size = new System.Drawing.Size(352, 26);
            this.cmbWallets.TabIndex = 1;
            // 
            // kryptonLabel2
            // 
            this.kryptonLabel2.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.kryptonLabel2.Location = new System.Drawing.Point(75, 60);
            this.kryptonLabel2.Name = "kryptonLabel2";
            this.kryptonLabel2.Size = new System.Drawing.Size(63, 24);
            this.kryptonLabel2.TabIndex = 2;
            this.kryptonLabel2.Values.Text = global::DemoTradingApp.Properties.Resources.Amount;
            // 
            // numAmount
            // 
            this.numAmount.AllowDecimals = true;
            this.numAmount.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.numAmount.DecimalPlaces = 2;
            this.numAmount.Increment = new decimal(new int[] {
            100,
            0,
            0,
            0});
            this.numAmount.Location = new System.Drawing.Point(144, 59);
            this.numAmount.Maximum = new decimal(new int[] {
            1410065407,
            2,
            0,
            0});
            this.numAmount.Name = "numAmount";
            this.numAmount.Size = new System.Drawing.Size(352, 26);
            this.numAmount.TabIndex = 3;
            // 
            // kryptonLabel3
            // 
            this.kryptonLabel3.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.kryptonLabel3.Location = new System.Drawing.Point(62, 104);
            this.kryptonLabel3.Name = "kryptonLabel3";
            this.kryptonLabel3.Size = new System.Drawing.Size(76, 24);
            this.kryptonLabel3.TabIndex = 4;
            this.kryptonLabel3.Values.Text = global::DemoTradingApp.Properties.Resources.Currency;
            // 
            // cmbCurrency
            // 
            this.cmbCurrency.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.cmbCurrency.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCurrency.DropDownWidth = 217;
            this.cmbCurrency.IntegralHeight = false;
            this.cmbCurrency.Location = new System.Drawing.Point(144, 103);
            this.cmbCurrency.Name = "cmbCurrency";
            this.cmbCurrency.Size = new System.Drawing.Size(352, 26);
            this.cmbCurrency.TabIndex = 5;
            // 
            // btnConfirm
            // 
            this.btnConfirm.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnConfirm.Location = new System.Drawing.Point(240, 142);
            this.btnConfirm.Name = "btnConfirm";
            this.btnConfirm.Size = new System.Drawing.Size(160, 37);
            this.btnConfirm.TabIndex = 6;
            this.btnConfirm.Values.Text = global::DemoTradingApp.Properties.Resources.ConfirmAddBalance;
            this.btnConfirm.Click += new System.EventHandler(this.btnConfirm_Click);
            // 
            // groupRemoveBalance
            // 
            this.groupRemoveBalance.CaptionStyle = Krypton.Toolkit.LabelStyle.TitleControl;
            this.groupRemoveBalance.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupRemoveBalance.Location = new System.Drawing.Point(3, 243);
            this.groupRemoveBalance.Name = "groupRemoveBalance";
            // 
            // groupRemoveBalance.Panel
            // 
            this.groupRemoveBalance.Panel.Controls.Add(this.tableLayoutPanelRemove);
            this.groupRemoveBalance.Size = new System.Drawing.Size(508, 194);
            this.groupRemoveBalance.TabIndex = 1;
            this.groupRemoveBalance.Values.Heading = global::DemoTradingApp.Properties.Resources.RemoveBalance;
            // 
            // tableLayoutPanelRemove
            // 
            this.tableLayoutPanelRemove.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanelRemove.ColumnCount = 2;
            this.tableLayoutPanelRemove.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanelRemove.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanelRemove.Controls.Add(this.kryptonLabel4, 0, 0);
            this.tableLayoutPanelRemove.Controls.Add(this.cmbAssetToRemove, 1, 0);
            this.tableLayoutPanelRemove.Controls.Add(this.kryptonLabel5, 0, 1);
            this.tableLayoutPanelRemove.Controls.Add(this.numAmountToRemove, 1, 1);
            this.tableLayoutPanelRemove.Controls.Add(this.btnRemoveBalance, 1, 2);
            this.tableLayoutPanelRemove.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanelRemove.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanelRemove.Name = "tableLayoutPanelRemove";
            this.tableLayoutPanelRemove.Padding = new System.Windows.Forms.Padding(5);
            this.tableLayoutPanelRemove.RowCount = 3;
            this.tableLayoutPanelRemove.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.tableLayoutPanelRemove.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.tableLayoutPanelRemove.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.tableLayoutPanelRemove.Size = new System.Drawing.Size(504, 147);
            this.tableLayoutPanelRemove.TabIndex = 0;
            // 
            // kryptonLabel4
            // 
            this.kryptonLabel4.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.kryptonLabel4.Location = new System.Drawing.Point(8, 15);
            this.kryptonLabel4.Name = "kryptonLabel4";
            this.kryptonLabel4.Size = new System.Drawing.Size(183, 24);
            this.kryptonLabel4.TabIndex = 0;
            this.kryptonLabel4.Values.Text = global::DemoTradingApp.Properties.Resources.AssetToRemove;
            // 
            // cmbAssetToRemove
            // 
            this.cmbAssetToRemove.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.cmbAssetToRemove.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbAssetToRemove.DropDownWidth = 217;
            this.cmbAssetToRemove.IntegralHeight = false;
            this.cmbAssetToRemove.Location = new System.Drawing.Point(197, 14);
            this.cmbAssetToRemove.Name = "cmbAssetToRemove";
            this.cmbAssetToRemove.Size = new System.Drawing.Size(299, 26);
            this.cmbAssetToRemove.TabIndex = 1;
            // 
            // kryptonLabel5
            // 
            this.kryptonLabel5.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.kryptonLabel5.Location = new System.Drawing.Point(58, 59);
            this.kryptonLabel5.Name = "kryptonLabel5";
            this.kryptonLabel5.Size = new System.Drawing.Size(133, 24);
            this.kryptonLabel5.TabIndex = 2;
            this.kryptonLabel5.Values.Text = global::DemoTradingApp.Properties.Resources.AmountToRemove;
            // 
            // numAmountToRemove
            // 
            this.numAmountToRemove.AllowDecimals = true;
            this.numAmountToRemove.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.numAmountToRemove.DecimalPlaces = 6;
            this.numAmountToRemove.Location = new System.Drawing.Point(197, 58);
            this.numAmountToRemove.Maximum = new decimal(new int[] {
            10000000,
            0,
            0,
            0});
            this.numAmountToRemove.Name = "numAmountToRemove";
            this.numAmountToRemove.Size = new System.Drawing.Size(299, 26);
            this.numAmountToRemove.TabIndex = 3;
            // 
            // btnRemoveBalance
            // 
            this.btnRemoveBalance.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnRemoveBalance.Location = new System.Drawing.Point(266, 99);
            this.btnRemoveBalance.Name = "btnRemoveBalance";
            this.btnRemoveBalance.Size = new System.Drawing.Size(160, 37);
            this.btnRemoveBalance.TabIndex = 4;
            this.btnRemoveBalance.Values.Text = global::DemoTradingApp.Properties.Resources.ConfirmRemoveBalance;
            this.btnRemoveBalance.Click += new System.EventHandler(this.btnRemoveBalance_Click);
            // 
            // btnCancel
            // 
            this.btnCancel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Location = new System.Drawing.Point(177, 471);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(160, 42);
            this.btnCancel.TabIndex = 2;
            this.btnCancel.Values.Text = global::DemoTradingApp.Properties.Resources.Close;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // AddBalanceForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(534, 561);
            this.Controls.Add(this.kryptonPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "AddBalanceForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = global::DemoTradingApp.Properties.Resources.BalanceManagement;
            this.Load += new System.EventHandler(this.AddBalanceForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.kryptonPanel1)).EndInit();
            this.kryptonPanel1.ResumeLayout(false);
            this.mainTableLayoutPanel.ResumeLayout(false);
            this.mainTableLayoutPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.groupAddBalance.Panel)).EndInit();
            this.groupAddBalance.Panel.ResumeLayout(false);
            this.tableLayoutPanelAdd.ResumeLayout(false);
            this.tableLayoutPanelAdd.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.groupAddBalance)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmbWallets)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmbCurrency)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.groupRemoveBalance.Panel)).EndInit();
            this.groupRemoveBalance.Panel.ResumeLayout(false);
            this.tableLayoutPanelRemove.ResumeLayout(false);
            this.tableLayoutPanelRemove.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.groupRemoveBalance)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmbAssetToRemove)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Krypton.Toolkit.KryptonManager kryptonManager1;
        private Krypton.Toolkit.KryptonPanel kryptonPanel1;
        private System.Windows.Forms.TableLayoutPanel mainTableLayoutPanel;
        private Krypton.Toolkit.KryptonGroupBox groupAddBalance;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanelAdd;
        private Krypton.Toolkit.KryptonLabel kryptonLabel1;
        private Krypton.Toolkit.KryptonComboBox cmbWallets;
        private Krypton.Toolkit.KryptonLabel kryptonLabel2;
        private Krypton.Toolkit.KryptonNumericUpDown numAmount;
        private Krypton.Toolkit.KryptonLabel kryptonLabel3;
        private Krypton.Toolkit.KryptonComboBox cmbCurrency;
        private Krypton.Toolkit.KryptonButton btnConfirm;
        private Krypton.Toolkit.KryptonGroupBox groupRemoveBalance;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanelRemove;
        private Krypton.Toolkit.KryptonLabel kryptonLabel4;
        private Krypton.Toolkit.KryptonComboBox cmbAssetToRemove;
        private Krypton.Toolkit.KryptonLabel kryptonLabel5;
        private Krypton.Toolkit.KryptonNumericUpDown numAmountToRemove;
        private Krypton.Toolkit.KryptonButton btnRemoveBalance;
        private Krypton.Toolkit.KryptonButton btnCancel;
    }
}
